version: '3.3'

services:
  python_backend:
    build:
      context: ./python_services
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: cinemacondo  # Change DB name 
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 181018  # Change password
      DATABASE_HOST: localhost # host.docker.internal if it's windows
      DATABASE_PORT: 5432
    network_mode: "host"
    # networks:
    #   - local -> if it's windows

  java_backend:
    build:
      context: ./java_services
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cinemacondo #same as up
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 181018  
    network_mode: "host"
    # networks:
    #   - local -> if it's windows

    

networks:
  local:
    driver: bridge
