spring.application.name=java_services
server.port=8001
spring.datasource.url=jdbc:postgresql://localhost:5432/cinemaDB
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
stripe.key=sk_test_51QrpaBHmjBBWCeEPNo36QM0d9qoZsMpwQbFOg0TabeFRGdwddGQZOinfMfdkYIH4mBPhsnnF1794gtP7u0INeHkk00GfJPyRsl
paypal.client.id=AciFveK1G4Du8WhT6jEJDr19299rtpc0SN9Mg3ob_7tLGkBnhosbP-qs4KNxhrcZUkpVWBRfN4k-xUP-
paypal.client.secret=EBNa11qxy8kfZo6fi7otIBS16BhZl1Gg8gK5_WNtF3W3Fz1E0wPIAN0ZKk2pwHnxCMOK6o3JClpvxG6O
paypal.mode=sandbox