[project]
name = "backend-python"
version = "0.1.0"
description = "This is the backend of a project about a system for managing a cinema"
authors = [
    {name = "Alejandro Nuñez",email = "anunezb@udistrital.edu.co"},
    {name = "Miguel Sanabria",email = "masanabriap@udistrital.edu.co"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.115.8,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "psycopg2 (>=2.9.10,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pylint = "^3.3.4"
black = "^25.1.0"
pre-commit = "^4.1.0"
pytest = "^8.3.4"

